### ISSUE TITLE
Ingress smoke test

### ISSUE THREAD

**Issue by drewwells** [infobloxopen/konk#117]
We need a way to verify ingress functionality running in a cluster. The approach needs to be independent of DNS records as devops does not support a declarative DNS model

The simplest way would be to start a pod in-cluster, issue calls directly to ingress controller with HOST header of our ingress route. Controller routes calls to this hostname to the correct Konk instance. Ingress object would be started with some KONK url fake or otherwise ie. konk.example.infoblox.com.

`curl '--header Host: konk.example.infoblox.com' -H 'Authorization: {identity trusted creds}' http://localhost:80/apis/example.infoblox.com/v1alpha1/namespaces/default/contacts?limit=500`

*A/C*
- ingress setup works in-cluster
- smoke test works with kubectl access or in-cluster

**Comment by kd7lxl** [comment]
Your example is a bit wrong. You wouldn't use the certs like that, since the ingress controller adds them to the request while proxying.
```
curl -H 'Host: localhost' -H 'Authorization: Bearer fake' -H 'X-Remote-User: foo' -H 'X-Remote-Group: bar' http://<ingress-service-ip>:80/apis/example.infoblox.com/v1alpha1/namespaces/default/contacts?limit=500
```

**Comment by drewwells** [comment]
updated auth headers, x-remote-* doesn't need to be verified as part of this

**Comment by drewwells** [comment]
Basic test has been added. We may need to improve client verification in the example-apiserver
https://github.com/infobloxopen/konk/blob/main/helm-charts/example-apiserver/templates/tests/test-connection.yaml#L42-L43
